fix id length first commit
starhugegraph/hugegraph-computer pull request #41
Opened 2021-11-02 12:59 UTC by yandababa2

2021-11-03 08:48 UTC, zxxxhonest commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/compute/FileGraphPartition.java
> +        while (this.vertexInput.hasNext()) {
不需要遍历点

2021-11-03 08:49 UTC, zxxxhonest commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/compute/FileGraphPartition.java
> +                long nid = (((long)partitionID) << 32) |
id长度可以优化，多一个字节100亿边就多10GB

2021-11-03 08:49 UTC, zxxxhonest commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/compute/FileGraphPartition.java
> +                idHash.put(originId, newId);
hashmap可能造成内存不足

2021-11-03 08:53 UTC, zxxxhonest commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/compute/FileGraphPartition.java
> +                Id id = this.context.graphFactory().createId(nid);
过滤掉出边

2021-11-03 08:55 UTC, zxxxhonest commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/compute/FileGraphPartition.java
> +    public void partitionHashId() {
hashid可以改成shortid

2021-11-03 09:28 UTC, zxxxhonest commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/compute/output/EdgesOutput.java
> +    public EdgesOutput(ComputerContext context, File edgeFile) {
序列化反序列化需要集中处理，分散容易改漏

2021-11-03 10:13 UTC, coderzc requested changes

2021-11-03 10:13 UTC, coderzc commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/worker/WorkerService.java
> +            WorkerContext context0 = new SuperstepContext(-3, superstepStat);
让 SUPERSTEP 单调递增，否则可能导致不可预料的问题

2021-11-03 10:13 UTC, coderzc commented on computer-core/src/main/java/com/baidu/hugegraph/computer/core/worker/WorkerService.java
> +            this.bsp4Worker.workerStepPrepareDone(-3);
定义常量，不要使用硬编码

2021-11-29 12:53 UTC, zxxxhonest approved these changes

2021-11-29 12:53 UTC, merged