add filter blank value hdfs output
starhugegraph/hugegraph-computer pull request #48
Opened 2021-11-09 07:11 UTC by corgiboygsj

2021-11-09 07:18 UTC, coderzc requested changes

2021-11-09 07:18 UTC, coderzc commented on computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/path/links/LinksValue.java
> +               Constants.EMPTY_STR;
可以移到string()

2021-11-09 13:44 UTC, zxxxhonest approved these changes

2021-11-10 03:20 UTC, zxxxhonest approved these changes

2021-11-10 06:06 UTC, coderzc approved these changes

2021-11-10 06:16 UTC, merged